services:
  bind:
    build:
      context: ./bind
      dockerfile: Dockerfile
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - bind_cache:/var/cache/bind
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/m1-9.zone:/etc/bind/m1-9.zone
  nginx:
    build:
      context: ./web/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx/html:/var/www/html
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./web/mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mysql
  php:
    build:
      context: ./web/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./web/nginx/html/www:/var/www/html/www

volumes:
  bind_cache:
  mariadb_data:
