services:
  bind:
    build:
      context: ./bind
      dockerfile: Dockerfile
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - bind_cache:/var/cache/bind
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/m1-9.zone:/etc/bind/m1-9.zone
  nginx:
    build:
      context: ./web/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

volumes:
  bind_cache:
